apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.port }}
  selector:
    app: {{ .Values.redis.name }}
