app:
  name: redis-crud-service
  replicas: 1
  image:
    repository: jin105/redis-crud-service
    tag: latest
    pullPolicy: IfNotPresent
  port: 4567

redis:
  name: redis
  replicas: 1
  image:
    repository: redis
    tag: 6.2.5
    pullPolicy: IfNotPresent
  port: 6379
  service:
    name: redis
    port: 6379
